export const OFFICIAL_THEMES = [
  {
    id: "cloud-neumorphism",
    name: "Cloud Neumorphism",
    style: "Soft light-gray neumorphism",
    bg: "#E6EAF0",
    surface: "#E6EAF0",
    textPrimary: "#283142",
    textSecondary: "#66748A",
    accent: "#5869D8",
    incomingMsg: "#E6EAF0",
    incomingMsgText: "#283142",
    outgoingMsg: "#5869D8",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#D2D9E3",
    isDark: false,
  },
  {
    id: "midnight-slate",
    name: "Midnight Slate",
    style: "Professional dark slate",
    bg: "#151922",
    surface: "#1D2330",
    textPrimary: "#F1F5F9",
    textSecondary: "#B0BDCF",
    accent: "#7DA8FF",
    incomingMsg: "#252D3B",
    incomingMsgText: "#F1F5F9",
    outgoingMsg: "#365CCB",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#343E50",
    isDark: true,
  },
  {
    id: "pure-snow",
    name: "Pure Snow",
    style: "Minimal clean white interface",
    bg: "#F8FAFC",
    surface: "#FFFFFF",
    textPrimary: "#172033",
    textSecondary: "#526174",
    accent: "#3159C9",
    incomingMsg: "#F0F3F8",
    incomingMsgText: "#172033",
    outgoingMsg: "#3159C9",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#DCE3ED",
    isDark: false,
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    style: "Cyberpunk dark with vivid teal",
    bg: "#0B1020",
    surface: "#141C30",
    textPrimary: "#F0F5FF",
    textSecondary: "#B2C1DA",
    accent: "#52F7D4",
    incomingMsg: "#1A2640",
    incomingMsgText: "#F0F5FF",
    outgoingMsg: "#263D73",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#30415C",
    isDark: true,
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    style: "Soft lavender purple aesthetic",
    bg: "#F1EEFA",
    surface: "#FBF9FF",
    textPrimary: "#302747",
    textSecondary: "#685E7E",
    accent: "#7652C8",
    incomingMsg: "#E9E2F7",
    incomingMsgText: "#302747",
    outgoingMsg: "#7652C8",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#D9D0EC",
    isDark: false,
  },
  {
    id: "sakura-blossom",
    name: "Sakura Blossom",
    style: "Pastel pink with rose accents",
    bg: "#FFF1F4",
    surface: "#FFFFFF",
    textPrimary: "#462B38",
    textSecondary: "#785A68",
    accent: "#C44575",
    incomingMsg: "#FBE1E9",
    incomingMsgText: "#462B38",
    outgoingMsg: "#B8376A",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#EBD0DA",
    isDark: false,
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    style: "Calm blue & teal aesthetic",
    bg: "#EAF5F8",
    surface: "#F8FCFD",
    textPrimary: "#193746",
    textSecondary: "#4F6E7C",
    accent: "#087E8B",
    incomingMsg: "#DCEEF3",
    incomingMsgText: "#193746",
    outgoingMsg: "#087E8B",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#C9E0E7",
    isDark: false,
  },
  {
    id: "forest-moss",
    name: "Forest Moss",
    style: "Nature-inspired forest green",
    bg: "#EAF0E8",
    surface: "#F5F8F2",
    textPrimary: "#24382B",
    textSecondary: "#5B6D60",
    accent: "#356B45",
    incomingMsg: "#DCE8D9",
    incomingMsgText: "#24382B",
    outgoingMsg: "#356B45",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#CCD9C9",
    isDark: false,
  },
  {
    id: "sunset-ember",
    name: "Sunset Ember",
    style: "Warm sunset terracotta palette",
    bg: "#FFF2E8",
    surface: "#FFFAF5",
    textPrimary: "#462B23",
    textSecondary: "#795B50",
    accent: "#B94F2C",
    incomingMsg: "#F9E2D3",
    incomingMsgText: "#462B23",
    outgoingMsg: "#B94F2C",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#EAD2C2",
    isDark: false,
  },
  {
    id: "amoled-graphite",
    name: "AMOLED Graphite",
    style: "Deep AMOLED black & violet",
    bg: "#08090D",
    surface: "#12141C",
    textPrimary: "#F5F5FA",
    textSecondary: "#B5B9C9",
    accent: "#A78BFA",
    incomingMsg: "#1B1D28",
    incomingMsgText: "#F5F5FA",
    outgoingMsg: "#6246C7",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#303240",
    isDark: true,
  },
];

export const THEMES = OFFICIAL_THEMES.map((t) => t.id);