export const OFFICIAL_THEMES = [
  {
    id: "cloud-neumorphism",
    name: "Cloud Neumorphism",
    style: "Soft light-gray neumorphism",
    bg: "#E6EAF0",
    surface: "#E6EAF0",
    textPrimary: "#283142",
    textSecondary: "#66748A",
    accent: "#5869D8",
    incomingMsg: "#E6EAF0",
    incomingMsgText: "#283142",
    outgoingMsg: "#5869D8",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#D2D9E3",
    isDark: false,
  },
  {
    id: "midnight-slate",
    name: "Midnight Slate",
    style: "Professional charcoal slate with icy blue accents",
    bg: "#11151C",
    surface: "#1A202B",
    textPrimary: "#EDF2F9",
    textSecondary: "#A3B0C2",
    accent: "#5B8DEF",
    incomingMsg: "#242D3A",
    incomingMsgText: "#EDF2F9",
    outgoingMsg: "#3A67D8",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#2E3748",
    isDark: true,
  },
  {
    id: "pure-snow",
    name: "Pure Snow",
    style: "Minimal clean white interface with crisp blue accents",
    bg: "#F8FAFC",
    surface: "#FFFFFF",
    textPrimary: "#0F172A",
    textSecondary: "#475569",
    accent: "#2563EB",
    incomingMsg: "#F1F5F9",
    incomingMsgText: "#0F172A",
    outgoingMsg: "#2563EB",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#E2E8F0",
    isDark: false,
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    style: "Futuristic dark theme with vivid electric cyan",
    bg: "#070B16",
    surface: "#0F1626",
    textPrimary: "#E0F7FE",
    textSecondary: "#88A4C2",
    accent: "#00F5D4",
    incomingMsg: "#16233B",
    incomingMsgText: "#E0F7FE",
    outgoingMsg: "#0F4C5C",
    outgoingMsgText: "#00F5D4",
    borderColor: "#1D2E4A",
    isDark: true,
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    style: "Soft lilac & violet pastel aesthetic",
    bg: "#F3EFFB",
    surface: "#FCFAFF",
    textPrimary: "#2E2342",
    textSecondary: "#6E6085",
    accent: "#7C3AED",
    incomingMsg: "#E8DEF8",
    incomingMsgText: "#2E2342",
    outgoingMsg: "#7C3AED",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#DDD2F2",
    isDark: false,
  },
  {
    id: "forest-moss",
    name: "Forest Moss",
    style: "Nature-inspired sage & deep emerald green",
    bg: "#E9EFE6",
    surface: "#F6FAF3",
    textPrimary: "#1C2E22",
    textSecondary: "#526658",
    accent: "#2E6B40",
    incomingMsg: "#D7E5D4",
    incomingMsgText: "#1C2E22",
    outgoingMsg: "#2E6B40",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#C8D8C6",
    isDark: false,
  },
  {
    id: "coffee-house",
    name: "Coffee House",
    style: "Rich espresso brown with warm caramel accents",
    bg: "#1E1713",
    surface: "#2A201A",
    textPrimary: "#F6E9DA",
    textSecondary: "#C4AA93",
    accent: "#D99B56",
    incomingMsg: "#382B23",
    incomingMsgText: "#F6E9DA",
    outgoingMsg: "#8C5635",
    outgoingMsgText: "#FFF6ED",
    borderColor: "#47362C",
    isDark: true,
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    style: "Calm sea glass with deep ocean teal accents",
    bg: "#EBF5F7",
    surface: "#FAFDFF",
    textPrimary: "#143440",
    textSecondary: "#4C6E7A",
    accent: "#0284C7",
    incomingMsg: "#D9ECF2",
    incomingMsgText: "#143440",
    outgoingMsg: "#0284C7",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#C5DFE7",
    isDark: false,
  },
  {
    id: "sunset-ember",
    name: "Sunset Ember",
    style: "Warm terracotta & golden sunset ember",
    bg: "#FFF3EC",
    surface: "#FFFBF8",
    textPrimary: "#45261C",
    textSecondary: "#825C4E",
    accent: "#EA580C",
    incomingMsg: "#F8DFD2",
    incomingMsgText: "#45261C",
    outgoingMsg: "#C2410C",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#EBD1C1",
    isDark: false,
  },
  {
    id: "amoled-graphite",
    name: "AMOLED Graphite",
    style: "True black AMOLED with vivid purple accents",
    bg: "#000000",
    surface: "#0F0F12",
    textPrimary: "#FAFAFA",
    textSecondary: "#A1A1AA",
    accent: "#A855F7",
    incomingMsg: "#18181B",
    incomingMsgText: "#FAFAFA",
    outgoingMsg: "#7E22CE",
    outgoingMsgText: "#FFFFFF",
    borderColor: "#27272A",
    isDark: true,
  },
];

export const THEMES = OFFICIAL_THEMES.map((t) => t.id);